<?php
declare(strict_types=1);
namespace Ferb\Conf\Providers;

interface ConfigProviderInterface
{
    /**
     * gets a configuration value for the specified key.
     *
     * @return array [$success bool, $value mixed]
     */
    public function get(string $key): array;
    /**
     * Returns the immediate descendant configuration keys for the given parent path
     * based on this provider's data and the set of keys returned by the preceeding
     * providers
     *
     * @param array $previous_keys keys generated by the preceeding providers
     * @param string $parent_path the parent path
     * @return array the child keys
     */
    public function get_child_keys(array $previous_keys, string $parent_path) : iterable;

}
